DROP TABLE IF EXISTS performance;
DROP TABLE IF EXISTS references_;
DROP TABLE IF EXISTS qa_results;
DROP TABLE IF EXISTS assets;
DROP TABLE IF EXISTS costs;
DROP TABLE IF EXISTS job_steps;
DROP TABLE IF EXISTS jobs;
